import React, { createContext, useContext, useState } from 'react';

export const LANGS = {
  en: 'English',
  hi: 'हिंदी',
  mr: 'मराठी',
};

export const T = {
  en: {
    appName: 'FasalRaksha — Crop Insurance Portal',
    appSub: 'FasalRaksha · AI-Powered Crop Protection',
    farmer: 'Farmer',
    govtOfficer: 'Government Officer',
    signIn: 'Sign In',
    register: 'Register',
    email: 'Email Address',
    password: 'Password',
    fullName: 'Full Name',
    govtKey: 'Government Access Key',
    govtKeyPlaceholder: 'Enter issued access key',
    noAccount: "Don't have an account?",
    haveAccount: 'Already have an account?',
    registerHere: 'Register here',
    signInHere: 'Sign in here',
    createAccount: 'Create Account',
    invalidKey: 'Invalid government access key',
    dashboard: 'Dashboard',
    farmers: 'Farmers Registry',
    claims: 'Claims',
    fraud: 'Fraud Analysis',
    weather: 'Weather & NDVI',
    submitClaim: 'Submit Claim',
    myClaims: 'My Claims',
    myDashboard: 'My Dashboard',
    signOut: 'Sign Out',
    govtOfficerRole: 'Govt. Officer',
    farmerRole: 'Farmer',
    totalFarmers: 'Total Farmers',
    totalClaims: 'Total Claims',
    highRisk: 'High Risk Claims',
    approved: 'Approved Claims',
    pending: 'Pending Review',
    avgSettlement: 'Avg. Settlement',
    totalPayout: 'Total Payout Disbursed',
    recentClaims: 'Recent Claims',
    fraudScore: 'Fraud Score',
    risk: 'Risk',
    status: 'Status',
    district: 'District',
    lossType: 'Loss Type',
    estLoss: 'Est. Loss',
    payout: 'Payout',
    viewAll: 'View All',
    loading: 'Loading…',
    backendError: 'Backend unreachable — start Flask on port 5000.',
    registered: 'Registered',
    allTime: 'All time',
    fraudRate: 'fraud rate',
    awaitingAction: 'Awaiting action',
    cleared: 'Cleared',
    acrossApproved: 'Across all approved & pre-approved claims',
    selectLanguage: 'Language',
    aadhaar: 'Aadhaar Number',
    phone: 'Phone',
    village: 'Village',
    landArea: 'Land Area (ha)',
    crop: 'Primary Crop',
    registerFarmer: 'Register Farmer',
    newFarmerReg: 'New Farmer Registration',
    noFarmers: 'No farmers registered yet',
    noClaims: 'No claims yet',
    selectFarmer: 'Select Farmer',
    notes: 'Notes',
    imageUrl: 'Field Photo URL',
    submitAnalyze: 'Submit & Analyze Claim',
    claimSubmitted: 'Claim Submitted',
    viewClaim: 'View Claim',
    submitAnother: 'Submit Another',
    ndviScore: 'NDVI Score',
    weatherScore: 'Weather Score',
    preApprovedPayout: 'Pre-Approved Payout',
    inputParams: 'Input Parameters',
    analysisResult: 'Analysis Result',
    runAnalysis: 'Run Fraud Analysis',
    analyzing: 'Analyzing…',
    rulesTriggered: 'Rules Triggered',
    recommendation: 'Recommendation',
    noFraudIndicators: 'No fraud indicators detected',
    flagReview: 'FLAG FOR MANUAL REVIEW — Do not auto-approve',
    proceed: 'PROCEED — Low risk, eligible for pre-approval',
    fraudRules: 'Fraud Detection Rules',
    officerPanel: 'Officer Review Panel',
    updateStatus: 'Update Status',
    payoutAmount: 'Payout Amount (₹)',
    officerNotes: 'Officer Notes',
    updateClaim: 'Update Claim',
    farmerDetails: 'Farmer Details',
    claimAnalysis: 'Claim Analysis Data',
    backToClaims: '← Back to Claims',
    name: 'Name',
    land: 'Land',
    claimDate: 'Claim Date',
    healthyVeg: 'Healthy vegetation',
    moderateStress: 'Moderate stress',
    severeStress: 'Severe stress',
    weatherSeverity: 'Weather Severity',
    ndviRef: 'NDVI Reference Scale',
    selectDistrict: 'Select a district to fetch live data',
    weatherData: 'OpenWeather Data',
    satelliteNdvi: 'Satellite NDVI',
    temperature: 'Temperature',
    humidity: 'Humidity',
    rainfall: 'Rainfall',
    conditions: 'Conditions',
    recentFarmers: 'Recent Farmers',
    farmStats: 'Farm Statistics',
    avgLandArea: 'Avg. Land Area',
    topCrop: 'Top Crop',
    humanAuthority: 'Human authority retained — no automatic rejection. Officers make the final decision.'
  },
  hi: {
    appName: 'फसलरक्षा — फसल बीमा पोर्टल',
    appSub: 'फसलरक्षा · AI-संचालित फसल सुरक्षा',
    farmer: 'किसान',
    govtOfficer: 'सरकारी अधिकारी',
    signIn: 'साइन इन करें',
    register: 'पंजीकरण करें',
    email: 'ईमेल पता',
    password: 'पासवर्ड',
    fullName: 'पूरा नाम',
    govtKey: 'सरकारी एक्सेस कुंजी',
    govtKeyPlaceholder: 'जारी की गई एक्सेस कुंजी दर्ज करें',
    noAccount: 'खाता नहीं है?',
    haveAccount: 'पहले से खाता है?',
    registerHere: 'यहाँ पंजीकरण करें',
    signInHere: 'यहाँ साइन इन करें',
    createAccount: 'खाता बनाएं',
    invalidKey: 'अमान्य सरकारी एक्सेस कुंजी',
    dashboard: 'डैशबोर्ड',
    farmers: 'किसान रजिस्ट्री',
    claims: 'दावे',
    fraud: 'धोखाधड़ी विश्लेषण',
    weather: 'मौसम और NDVI',
    submitClaim: 'दावा दर्ज करें',
    myClaims: 'मेरे दावे',
    myDashboard: 'मेरा डैशबोर्ड',
    signOut: 'साइन आउट',
    govtOfficerRole: 'सरकारी अधिकारी',
    farmerRole: 'किसान',
    totalFarmers: 'कुल किसान',
    totalClaims: 'कुल दावे',
    highRisk: 'उच्च जोखिम दावे',
    approved: 'स्वीकृत दावे',
    pending: 'समीक्षा लंबित',
    avgSettlement: 'औसत निपटान',
    totalPayout: 'कुल भुगतान',
    recentClaims: 'हाल के दावे',
    fraudScore: 'धोखाधड़ी स्कोर',
    risk: 'जोखिम',
    status: 'स्थिति',
    district: 'जिला',
    lossType: 'हानि प्रकार',
    estLoss: 'अनुमानित हानि',
    payout: 'भुगतान',
    viewAll: 'सभी देखें',
    loading: 'लोड हो रहा है…',
    backendError: 'बैकएंड अनुपलब्ध — Flask पोर्ट 5000 पर शुरू करें।',
    registered: 'पंजीकृत',
    allTime: 'सभी समय',
    fraudRate: 'धोखाधड़ी दर',
    awaitingAction: 'कार्रवाई की प्रतीक्षा',
    cleared: 'मंजूर',
    acrossApproved: 'सभी स्वीकृत दावों में',
    selectLanguage: 'भाषा',
    aadhaar: 'आधार संख्या',
    phone: 'फोन',
    village: 'गाँव',
    landArea: 'भूमि क्षेत्र (हेक्टेयर)',
    crop: 'मुख्य फसल',
    registerFarmer: 'किसान पंजीकृत करें',
    newFarmerReg: 'नया किसान पंजीकरण',
    noFarmers: 'अभी तक कोई किसान पंजीकृत नहीं',
    noClaims: 'अभी तक कोई दावा नहीं',
    selectFarmer: 'किसान चुनें',
    notes: 'नोट्स',
    imageUrl: 'खेत की फोटो URL',
    submitAnalyze: 'दावा जमा करें और विश्लेषण करें',
    claimSubmitted: 'दावा जमा हुआ',
    viewClaim: 'दावा देखें',
    submitAnother: 'और दावा जमा करें',
    ndviScore: 'NDVI स्कोर',
    weatherScore: 'मौसम स्कोर',
    preApprovedPayout: 'पूर्व-स्वीकृत भुगतान',
    inputParams: 'इनपुट पैरामीटर',
    analysisResult: 'विश्लेषण परिणाम',
    runAnalysis: 'धोखाधड़ी विश्लेषण चलाएं',
    analyzing: 'विश्लेषण हो रहा है…',
    rulesTriggered: 'नियम सक्रिय',
    recommendation: 'सिफारिश',
    noFraudIndicators: 'कोई धोखाधड़ी संकेतक नहीं',
    flagReview: 'मैन्युअल समीक्षा के लिए फ्लैग करें',
    proceed: 'आगे बढ़ें — कम जोखिम',
    fraudRules: 'धोखाधड़ी पहचान नियम',
    officerPanel: 'अधिकारी समीक्षा पैनल',
    updateStatus: 'स्थिति अपडेट करें',
    payoutAmount: 'भुगतान राशि (₹)',
    officerNotes: 'अधिकारी नोट्स',
    updateClaim: 'दावा अपडेट करें',
    farmerDetails: 'किसान विवरण',
    claimAnalysis: 'दावा विश्लेषण डेटा',
    backToClaims: '← दावों पर वापस',
    name: 'नाम',
    land: 'भूमि',
    claimDate: 'दावा तिथि',
    healthyVeg: 'स्वस्थ वनस्पति',
    moderateStress: 'मध्यम तनाव',
    severeStress: 'गंभीर तनाव',
    weatherSeverity: 'मौसम गंभीरता',
    ndviRef: 'NDVI संदर्भ स्केल',
    selectDistrict: 'लाइव डेटा के लिए जिला चुनें',
    weatherData: 'OpenWeather डेटा',
    satelliteNdvi: 'उपग्रह NDVI',
    temperature: 'तापमान',
    humidity: 'आर्द्रता',
    rainfall: 'वर्षा',
    conditions: 'स्थितियाँ',
    recentFarmers: 'हाल के किसान',
    farmStats: 'खेत सांख्यिकी',
    avgLandArea: 'औसत भूमि क्षेत्र',
    topCrop: 'शीर्ष फसल',
    humanAuthority: 'मानव अधिकार बनाए रखा — कोई स्वचालित अस्वीकृति नहीं.'
  },
  mr: {
    appName: 'फसलरक्षा — पीक विमा पोर्टल',
    appSub: 'फसलरक्षा · AI-चालित पीक संरक्षण',
    farmer: 'शेतकरी',
    govtOfficer: 'सरकारी अधिकारी',
    signIn: 'साइन इन करा',
    register: 'नोंदणी करा',
    email: 'ईमेल पत्ता',
    password: 'पासवर्ड',
    fullName: 'पूर्ण नाव',
    govtKey: 'सरकारी प्रवेश की',
    govtKeyPlaceholder: 'जारी केलेली प्रवेश की प्रविष्ट करा',
    noAccount: 'खाते नाही?',
    haveAccount: 'आधीच खाते आहे?',
    registerHere: 'येथे नोंदणी करा',
    signInHere: 'येथे साइन इन करा',
    createAccount: 'खाते तयार करा',
    invalidKey: 'अवैध सरकारी प्रवेश की',
    dashboard: 'डॅशबोर्ड',
    farmers: 'शेतकरी नोंदणी',
    claims: 'दावे',
    fraud: 'फसवणूक विश्लेषण',
    weather: 'हवामान आणि NDVI',
    submitClaim: 'दावा सादर करा',
    myClaims: 'माझे दावे',
    myDashboard: 'माझा डॅशबोर्ड',
    signOut: 'साइन आउट',
    govtOfficerRole: 'सरकारी अधिकारी',
    farmerRole: 'शेतकरी',
    totalFarmers: 'एकूण शेतकरी',
    totalClaims: 'एकूण दावे',
    highRisk: 'उच्च जोखीम दावे',
    approved: 'मंजूर दावे',
    pending: 'प्रलंबित समीक्षा',
    avgSettlement: 'सरासरी निपटारा',
    totalPayout: 'एकूण वितरित रक्कम',
    recentClaims: 'अलीकडील दावे',
    fraudScore: 'फसवणूक स्कोर',
    risk: 'जोखीम',
    status: 'स्थिती',
    district: 'जिल्हा',
    lossType: 'नुकसान प्रकार',
    estLoss: 'अंदाजे नुकसान',
    payout: 'देयक',
    viewAll: 'सर्व पहा',
    loading: 'लोड होत आहे…',
    backendError: 'बॅकएंड उपलब्ध नाही — Flask पोर्ट 5000 वर सुरू करा.',
    registered: 'नोंदणीकृत',
    allTime: 'सर्व वेळ',
    fraudRate: 'फसवणूक दर',
    awaitingAction: 'कारवाईची प्रतीक्षा',
    cleared: 'मंजूर',
    acrossApproved: 'सर्व मंजूर दाव्यांमध्ये',
    selectLanguage: 'भाषा',
    aadhaar: 'आधार क्रमांक',
    phone: 'फोन',
    village: 'गाव',
    landArea: 'जमीन क्षेत्र (हेक्टर)',
    crop: 'मुख्य पीक',
    registerFarmer: 'शेतकरी नोंदणी करा',
    newFarmerReg: 'नवीन शेतकरी नोंदणी',
    noFarmers: 'अद्याप कोणताही शेतकरी नोंदणीकृत नाही',
    noClaims: 'अद्याप कोणतेही दावे नाहीत',
    selectFarmer: 'शेतकरी निवडा',
    notes: 'नोट्स',
    imageUrl: 'शेताचा फोटो URL',
    submitAnalyze: 'दावा सादर करा आणि विश्लेषण करा',
    claimSubmitted: 'दावा सादर झाला',
    viewClaim: 'दावा पहा',
    submitAnother: 'आणखी दावा सादर करा',
    ndviScore: 'NDVI स्कोर',
    weatherScore: 'हवामान स्कोर',
    preApprovedPayout: 'पूर्व-मंजूर देयक',
    inputParams: 'इनपुट पॅरामीटर्स',
    analysisResult: 'विश्लेषण निकाल',
    runAnalysis: 'फसवणूक विश्लेषण चालवा',
    analyzing: 'विश्लेषण होत आहे…',
    rulesTriggered: 'नियम सक्रिय',
    recommendation: 'शिफारस',
    noFraudIndicators: 'कोणतेही फसवणूक संकेतक नाहीत',
    flagReview: 'मॅन्युअल तपासणीसाठी फ्लॅग करा',
    proceed: 'पुढे जा — कमी जोखीम',
    fraudRules: 'फसवणूक शोध नियम',
    officerPanel: 'अधिकारी समीक्षा पॅनेल',
    updateStatus: 'स्थिती अपडेट करा',
    payoutAmount: 'देयक रक्कम (₹)',
    officerNotes: 'अधिकारी नोट्स',
    updateClaim: 'दावा अपडेट करा',
    farmerDetails: 'शेतकरी तपशील',
    claimAnalysis: 'दावा विश्लेषण डेटा',
    backToClaims: '← दाव्यांकडे परत',
    name: 'नाव',
    land: 'जमीन',
    claimDate: 'दावा तारीख',
    healthyVeg: 'निरोगी वनस्पती',
    moderateStress: 'मध्यम ताण',
    severeStress: 'तीव्र ताण',
    weatherSeverity: 'हवामान तीव्रता',
    ndviRef: 'NDVI संदर्भ स्केल',
    selectDistrict: 'थेट डेटासाठी जिल्हा निवडा',
    weatherData: 'OpenWeather डेटा',
    satelliteNdvi: 'उपग्रह NDVI',
    temperature: 'तापमान',
    humidity: 'आर्द्रता',
    rainfall: 'पाऊस',
    conditions: 'परिस्थिती',
    humanAuthority: 'मानवी अधिकार राखला — कोणतीही स्वयंचलित नकार नाही.',
  },
};

const LangContext = createContext();

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('ci_lang') || 'en');
  const t = T[lang];
  const switchLang = (l) => { setLang(l); localStorage.setItem('ci_lang', l); };
  return (
    <LangContext.Provider value={{ lang, t, switchLang }}>
      {children}
    </LangContext.Provider>
  );
}

export const useLang = () => useContext(LangContext);
